version: '3.8'

services:
    app:
        build: .
        container_name: xdebug_example
        volumes:
            - .:/var/www/php
        ports:
            - '8080:8080'
        environment:
            - XDEBUG_HOST=host.docker.internal
        extra_hosts:
            - host.docker.internal:host-gateway
